version: '3.9'
services:
  analytics-service:
    build:
      context: ./analytics-service
    ports:
      - "8080:8080"
    depends_on:
      - chart-service

  chart-service:
    build:
      context: analytics-service/chart-generator
    ports:
      - "5000:5000"